export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const SET_PHONE = 'SET_PHONE';
export const SET_PHONE_SUCCESS = 'SET_PHONE_SUCCESS';
export const SET_PHONE_FAILED = 'SET_PHONE_FAILED';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_GOOGLEACCOUNT = 'GET_GOOGLEACCOUNT';
export const GET_GOOGLEACCOUNT_SUCCESS = 'GET_GOOGLEACCOUNT_SUCCESS';
export const GET_GOOGLEACCOUNT_FAILED = 'GET_GOOGLEACCOUNT_FAILED';

export const REGISTER_GOOGLEACCOUNT = 'REGISTER_GOOGLEACCOUNT';
export const REGISTER_GOOGLEACCOUNT_SUCCESS = 'REGISTER_GOOGLEACCOUNT_SUCCESS';
export const REGISTER_GOOGLEACCOUNT_FAILED = 'REGISTER_GOOGLEACCOUNT_FAILED';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';

export const NOTIFICATION_WORK = 'NOTIFICATION_WORK';
export const NOTIFICATION_WORK_SUCCESS = 'NOTIFICATION_WORK_SUCCESS';
export const NOTIFICATION_WORK_FAILED = 'NOTIFICATION_WORK_FAILED';



